name: release-docs
on:
  push:
    branches:
      - main
      - beta
    paths:
      - docs

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          yarn
          yarn build
          yarn generate

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_XROSS_DOCS }}'
          channelId: live
          projectId: xross-docs
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
